version: "3.8"
services:
  pipeline:
    build: .
    image: realtimesignlanguage/pipeline:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

