global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'pipeline'
    static_configs:
      - targets: ['pipeline:8000']
    metrics_path: /metrics

rule_files:
  - /etc/prometheus/alerting/prometheus_rules.yml

