name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest ruff mypy
      - name: Run tests
        run: |
          pytest -q
      - name: Lint (ruff)
        run: |
          ruff --version
          ruff check .
      - name: Type check (mypy)
        run: |
          mypy --version
          mypy packages --ignore-missing-imports --install-types --non-interactive

